### ISSUE TITLE
Problemi con server

### ISSUE THREAD

**Issue by Valerio1990** [danieleSantini/rubrica-telefonica-quattro#8]
Alberto Martinez, [10.03.21 15:55]
error:
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (default-cli) on project rubrica-telefonica: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:

errori nel controller:
metodi non pubblici
non request mapping in aggiorna rubrica

------------------------------------------------------------------------

--< it.iad2.quattro:rubrica-telefonica >-----------------
Building rubrica-telefonica 0.0.1-SNAPSHOT
--------------------------------[ jar ]---------------------------------

--- exec-maven-plugin:1.5.0:exec (default-cli) @ rubrica-telefonica --

Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (default-cli) on project rubrica-telefonica: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

//Versione nel esercizio auto fatto da lei
 exec-maven-plugin:3.0.0:exec (default-cli) @ gestauto ---

**Comment by luca-lezzerini** [comment]
Mi serve il copia e incolla di tutto la output lato server non soltanto di questa parte quindi vada su la finestra di output ci clicchi sopra col mouse premi control a in modo da selezionare tutto control c per copiare il selezionato e control v per incollare in un commento in questo ticket

**Comment by AlbertoMartinezMontero** [comment]
Grazie per la risposta, l'output completo:

cd C:\Users\alber\Documents\quattro\rubrica-quattro\rubrica-telefonica-quattro; "JAVA_HOME=C:\\Program Files\\Java\\jdk-15.0.1" cmd /c "\"C:\\Program Files\\NetBeans-12.1\\netbeans\\java\\maven\\bin\\mvn.cmd\" -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans-12.1\\netbeans\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 clean install"
Scanning for projects...

-----------------------< it.iad2:rubricaquattro >-----------------------
Building rubrica 0.0.1-SNAPSHOT
--------------------------------[ jar ]---------------------------------

--- maven-clean-plugin:3.1.0:clean (default-clean) @ rubricaquattro ---
Deleting C:\Users\alber\Documents\quattro\rubrica-quattro\rubrica-telefonica-quattro\target

--- maven-resources-plugin:3.2.0:resources (default-resources) @ rubricaquattro ---
Using 'UTF-8' encoding to copy filtered resources.
Using 'UTF-8' encoding to copy filtered properties files.
Copying 1 resource
Copying 0 resource

--- maven-compiler-plugin:3.8.1:compile (default-compile) @ rubricaquattro ---
Changes detected - recompiling the module!
Compiling 9 source files to C:\Users\alber\Documents\quattro\rubrica-quattro\rubrica-telefonica-quattro\target\classes

--- maven-resources-plugin:3.2.0:testResources (default-testResources) @ rubricaquattro ---
Using 'UTF-8' encoding to copy filtered resources.
Using 'UTF-8' encoding to copy filtered properties files.
skip non existing resourceDirectory C:\Users\alber\Documents\quattro\rubrica-quattro\rubrica-telefonica-quattro\src\test\resources

--- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ rubricaquattro ---
Changes detected - recompiling the module!
Compiling 1 source file to C:\Users\alber\Documents\quattro\rubrica-quattro\rubrica-telefonica-quattro\target\test-classes

--- maven-surefire-plugin:2.22.2:test (default-test) @ rubricaquattro ---
file.encoding cannot be set as system property, use <argLine>-Dfile.encoding=...</argLine> instead

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.iad2.gestauto.GestautoApplicationTests
19:00:45.840 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating CacheAwareContextLoaderDelegate from class [org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate]
19:00:45.867 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating BootstrapContext using constructor [public org.springframework.test.context.support.DefaultBootstrapContext(java.lang.Class,org.springframework.test.context.CacheAwareContextLoaderDelegate)]
19:00:45.944 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating TestContextBootstrapper for test class [it.iad2.gestauto.GestautoApplicationTests] from class [org.springframework.boot.test.context.SpringBootTestContextBootstrapper]
19:00:45.970 [main] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Neither @ContextConfiguration nor @ContextHierarchy found for test class [it.iad2.gestauto.GestautoApplicationTests], using SpringBootContextLoader
19:00:45.978 [main] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [it.iad2.gestauto.GestautoApplicationTests]: class path resource [it/iad2/gestauto/GestautoApplicationTests-context.xml] does not exist
19:00:45.979 [main] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [it.iad2.gestauto.GestautoApplicationTests]: class path resource [it/iad2/gestauto/GestautoApplicationTestsContext.groovy] does not exist
19:00:45.980 [main] INFO org.springframework.test.context.support.AbstractContextLoader - Could not detect default resource locations for test class [it.iad2.gestauto.GestautoApplicationTests]: no resource found for suffixes {-context.xml, Context.groovy}.
19:00:45.982 [main] INFO org.springframework.test.context.support.AnnotationConfigContextLoaderUtils - Could not detect default configuration classes for test class [it.iad2.gestauto.GestautoApplicationTests]: GestautoApplicationTests does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
19:00:46.083 [main] DEBUG org.springframework.test.context.support.ActiveProfilesUtils - Could not find an 'annotation declaring class' for annotation type [org.springframework.test.context.ActiveProfiles] and class [it.iad2.gestauto.GestautoApplicationTests]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.51 s <<< FAILURE! - in it.iad2.gestauto.GestautoApplicationTests
it.iad2.gestauto.GestautoApplicationTests  Time elapsed: 0.506 s  <<< ERROR!
java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test


Results:

Errors: 
  GestautoApplicationTests » IllegalState Unable to find a @SpringBootConfigurat...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time:  17.555 s
Finished at: 2021-03-10T19:00:46+01:00
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project rubricaquattro: There are test failures.

Please refer to C:\Users\alber\Documents\quattro\rubrica-quattro\rubrica-telefonica-quattro\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by AlbertoMartinezMontero** [comment]
Output completo del  Clean and Build project:
cd C:\Users\alber\Documents\quattro\rubrica-quattro\rubrica-telefonica-quattro; "JAVA_HOME=C:\\Program Files\\Java\\jdk-15.0.1" cmd /c "\"C:\\Program Files\\NetBeans-12.1\\netbeans\\java\\maven\\bin\\mvn.cmd\" -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans-12.1\\netbeans\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 clean install"
Scanning for projects...

-----------------------< it.iad2:rubricaquattro >-----------------------
Building rubrica 0.0.1-SNAPSHOT
--------------------------------[ jar ]---------------------------------

--- maven-clean-plugin:3.1.0:clean (default-clean) @ rubricaquattro ---
Deleting C:\Users\alber\Documents\quattro\rubrica-quattro\rubrica-telefonica-quattro\target

--- maven-resources-plugin:3.2.0:resources (default-resources) @ rubricaquattro ---
Using 'UTF-8' encoding to copy filtered resources.
Using 'UTF-8' encoding to copy filtered properties files.
Copying 1 resource
Copying 0 resource

--- maven-compiler-plugin:3.8.1:compile (default-compile) @ rubricaquattro ---
Changes detected - recompiling the module!
Compiling 9 source files to C:\Users\alber\Documents\quattro\rubrica-quattro\rubrica-telefonica-quattro\target\classes

--- maven-resources-plugin:3.2.0:testResources (default-testResources) @ rubricaquattro ---
Using 'UTF-8' encoding to copy filtered resources.
Using 'UTF-8' encoding to copy filtered properties files.
skip non existing resourceDirectory C:\Users\alber\Documents\quattro\rubrica-quattro\rubrica-telefonica-quattro\src\test\resources

--- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ rubricaquattro ---
Changes detected - recompiling the module!
Compiling 1 source file to C:\Users\alber\Documents\quattro\rubrica-quattro\rubrica-telefonica-quattro\target\test-classes

--- maven-surefire-plugin:2.22.2:test (default-test) @ rubricaquattro ---
file.encoding cannot be set as system property, use <argLine>-Dfile.encoding=...</argLine> instead

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.iad2.gestauto.GestautoApplicationTests
19:07:36.082 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating CacheAwareContextLoaderDelegate from class [org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate]
19:07:36.109 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating BootstrapContext using constructor [public org.springframework.test.context.support.DefaultBootstrapContext(java.lang.Class,org.springframework.test.context.CacheAwareContextLoaderDelegate)]
19:07:36.175 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating TestContextBootstrapper for test class [it.iad2.gestauto.GestautoApplicationTests] from class [org.springframework.boot.test.context.SpringBootTestContextBootstrapper]
19:07:36.195 [main] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Neither @ContextConfiguration nor @ContextHierarchy found for test class [it.iad2.gestauto.GestautoApplicationTests], using SpringBootContextLoader
19:07:36.203 [main] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [it.iad2.gestauto.GestautoApplicationTests]: class path resource [it/iad2/gestauto/GestautoApplicationTests-context.xml] does not exist
19:07:36.205 [main] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [it.iad2.gestauto.GestautoApplicationTests]: class path resource [it/iad2/gestauto/GestautoApplicationTestsContext.groovy] does not exist
19:07:36.205 [main] INFO org.springframework.test.context.support.AbstractContextLoader - Could not detect default resource locations for test class [it.iad2.gestauto.GestautoApplicationTests]: no resource found for suffixes {-context.xml, Context.groovy}.
19:07:36.207 [main] INFO org.springframework.test.context.support.AnnotationConfigContextLoaderUtils - Could not detect default configuration classes for test class [it.iad2.gestauto.GestautoApplicationTests]: GestautoApplicationTests does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
19:07:36.308 [main] DEBUG org.springframework.test.context.support.ActiveProfilesUtils - Could not find an 'annotation declaring class' for annotation type [org.springframework.test.context.ActiveProfiles] and class [it.iad2.gestauto.GestautoApplicationTests]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.501 s <<< FAILURE! - in it.iad2.gestauto.GestautoApplicationTests
it.iad2.gestauto.GestautoApplicationTests  Time elapsed: 0.499 s  <<< ERROR!
java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test


Results:

Errors: 
  GestautoApplicationTests » IllegalState Unable to find a @SpringBootConfigurat...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time:  15.824 s
Finished at: 2021-03-10T19:07:37+01:00
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project rubricaquattro: There are test failures.

Please refer to C:\Users\alber\Documents\quattro\rubrica-quattro\rubrica-telefonica-quattro\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by AlbertoMartinezMontero** [comment]
Problema risolto. Collegamento client server stabilito nelle 4 macchine dei componenti della squadra. Creato progetto parallelo con le stesse caratteristiche.
